version: '3'
services:
  mysql:
    container_name: mysql_db_todoapp
    image: mysql:8.0.32
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: tododatabase
    ports:
      - "3306:3306"
    volumes:
      - data_db_tododatabase:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  data_db_tododatabase:
    external: false