-- INSERT INTO todo (id, description,done, target_date, username) VALUES (10001,'Learn Docker', false, CURRENT_DATE(),'pblgllgs');
-- INSERT INTO todo (id, description,done, target_date, username) VALUES (10002,'Learn AWS', false, CURRENT_DATE(),'pblgllgs');
-- INSERT INTO todo (id, description,done, target_date, username) VALUES (10003,'Learn Node', false, CURRENT_DATE(),'pblgllgs');